swagger: '2.0'
info:
  version: 1.0.0
  title: Cards API
host: 40.79.18.220:8080
basePath: /v1/cards-management
schemes:
  - http
paths:
  '/cards':
    get:
      tags:
        - cards-controller
      summary: getCardsByUserId
      operationId: getCardsByUserIdUsingGET
      produces:
        - '*/*'
      parameters:
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ObfuscatedCardsResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/{user_uuid}/account/{account_uuid}/card/{card_uuid}':
    get:
      tags:
        - cards-controller
      summary: getCardByUserId
      operationId: getCardByUserIdUsingGET
      produces:
        - '*/*'
      parameters:
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
        - name: user_uuid
          in: path
          description: user_uuid
          required: true
          type: string
        - name: account_uuid
          in: path
          description: account_uuid
          required: true
          type: string
        - name: card_uuid
          in: path
          description: card_uuid
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CardInfoResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/cards/{cardId}':
    put:
      tags:
        - cards-controller
      summary: changeCardStatus
      operationId: changeCardStatusUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: cardId
          in: path
          description: cardId
          required: true
          type: string
        - in: body
          name: request
          description: request
          required: true
          schema:
            $ref: '#/definitions/ChangeCardStatusRequest'
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ObfuscatedCardsResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/cards/{cardId}/report':
    post:
      tags:
        - cards-controller
      summary: reportCardProblem
      operationId: reportCardProblemUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: cardId
          in: path
          description: cardId
          required: true
          type: string
        - in: body
          name: request
          description: request
          required: true
          schema:
            $ref: '#/definitions/ReportCardRequest'
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  ObfuscatedCardsResponse:
    type: object
    properties:
      id:
        type: string
      name_on_card:
        type: string
      pan:
        type: string
      status:
        type: string
      timestamps:
        $ref: '#/definitions/TimestampsExtDto'
    title: ObfuscatedCardsResponse
  TimestampsExtDto:
    type: object
    properties:
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
    title: TimestampsExtDto
  ChangeCardStatusRequest:
    type: object
    properties:
      cardId:
        type: string
        format: uuid
      status:
        type: string
        enum:
          - ACTIVE
          - LOCKED
          - CLOSED
          - EXPIRED
    title: ChangeCardStatusRequest
  CardInfoResponse:
    type: object
    properties:
      expiration_date:
        type: integer
        format: int32
      id:
        type: string
      name_on_card:
        type: string
      pan:
        type: string
      security_code:
        type: integer
        format: int32
      status:
        type: string
      timestamps:
        $ref: '#/definitions/TimestampsExtDto'
    title: CardInfoResponse
  ReportCardRequest:
    type: object
    properties:
      movements:
        type: string
        enum:
          - AFFIRMATIVE
          - NEGATIVE
      problem:
        type: string
        enum:
          - LOCK
          - REMISSION
    title: ReportCardRequest
    description: Request Data for decision making in regard of a card
