swagger: "2.0"
info:
  version: 1.0.0
  title: Identityprovider API
host: 40.123.26.42:8080
basePath: /v1/provider/users
schemes:
  - http
paths:
  /authentication/logout:
    post:
      produces:
        - application/json
      parameters:
        - name: access-token
          in: header
          required: true
          type: string
      responses:
        "200":
          description: 200 response
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "400":
          description: 400 response
          schema:
            $ref: "#/definitions/ResponseStatus"
        "401":
          description: 401 response
          schema:
            $ref: "#/definitions/ResponseStatus"
        "422":
          description: 422 response
          schema:
            $ref: "#/definitions/ResponseStatus"
        "500":
          description: 500 response
  /policies/password:
    get:
      produces:
        - application/json
      responses:
        "200":
          description: 200 response
          schema:
            $ref: "#/definitions/PasswordPattern"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "400":
          description: 400 response
          schema:
            $ref: "#/definitions/ResponseStatus"
        "401":
          description: 401 response
          schema:
            $ref: "#/definitions/ResponseStatus"
        "422":
          description: 422 response
          schema:
            $ref: "#/definitions/ResponseStatus"
        "500":
          description: 500 response
          schema:
            $ref: "#/definitions/ResponseStatus"
definitions:
  ResponseStatus:
    type: object
    properties:
      code:
        type: string
        description: The HTTP code
      message:
        type: string
        description: A description message
  PasswordPattern:
    type: object
    properties:
      regexLowerLetter:
        type: string
      regexUpperLetter:
        type: string
      regexNumber:
        type: string
      regexSpecialCharacter:
        type: string
      regexMinLength:
        type: string
