swagger: "2.0"
info:
  version: 1.0.0
  title: Notifications API
host: 52.179.169.65:8080
basePath: /v1/customer-management
schemes:
  - http
paths:
  /notification:
    get:
      produces:
        - application/json
      parameters:
        - name: access-token
          in: header
          required: true
          type: string
      responses:
        "200":
          description: 200 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "400":
          description: 400 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "401":
          description: 401 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "500":
          description: 500 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
  "/notification/{messageId}":
    put:
      operationId: updateNotificationUserByIdUsingPUT
      produces:
        - application/json
      parameters:
        - name: messageId
          in: path
          required: true
          type: string
        - name: access-token
          in: header
          required: true
          type: string
      responses:
        "200":
          description: 200 response
          schema:
            $ref: "#/definitions/MODELba1d6c"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "201":
          description: 201 response
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "401":
          description: 401 response
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "403":
          description: 403 response
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "404":
          description: 404 response
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
  /notification_setting/configuration:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: access-token
          in: header
          required: true
          type: string
        - in: body
          name: NotificationConfigDto
          required: true
          schema:
            $ref: "#/definitions/NotificationConfigDto"
      responses:
        "200":
          description: 200 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "400":
          description: 400 response
          schema:
            $ref: "#/definitions/ResponseStatus"
        "422":
          description: 422 response
        "500":
          description: 500 response
          schema:
            $ref: "#/definitions/ResponseStatus"
  "/notification_setting/{serviceId}/configuration":
    get:
      produces:
        - application/json
      parameters:
        - name: serviceId
          in: path
          required: true
          type: string
        - name: access-token
          in: header
          required: true
          type: string
      responses:
        "200":
          description: 200 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "400":
          description: 400 response
          schema:
            $ref: "#/definitions/ResponseStatus"
        "422":
          description: 422 response
        "500":
          description: 500 response
          schema:
            $ref: "#/definitions/ResponseStatus"
definitions:
  ResponseStatus:
    type: object
    properties:
      code:
        type: string
        description: The HTTP code
      message:
        type: string
        description: A description message
  MODELba1d6c:
    type: object
  NotificationConfigDto:
    type: object
    properties:
      operationType:
        type: string
      serviceId:
        type: string
        format: uuid
      whenDebtExist:
        type: boolean
      exactlyDate:
        type: string
        format: date-time
      dateMonth:
        type: string
