swagger: '2.0'
info:
  version: 1.0.0
  title: Api Documentation
host: 40.89.250.208:8080
basePath: /v1/payment-paypal
schemes:
  - http
paths:
  /v1/accounts:
    get:
      tags:
        - account-controller
      summary: getRetiroAccountByClientId
      operationId: getRetiroAccountByClientIdUsingGET
      produces:
        - application/json
      parameters:
        - name: client_id
          in: query
          description: client_id
          required: true
          type: integer
          format: int64
        - name: operation_type
          in: query
          description: operation_type
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /v1/accounts/by:
    get:
      tags:
        - account-controller
      summary: getRetiroAccountByEmail
      operationId: getRetiroAccountByEmailUsingGET
      produces:
        - application/json
      parameters:
        - name: email
          in: query
          description: email
          required: true
          type: string
        - name: operation_type
          in: query
          description: operation_type
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /v1/accounts/vinculation:
    get:
      tags:
        - account-controller
      summary: getClientVinculationLinkByEmail
      operationId: getClientVinculationLinkByEmailUsingGET
      produces:
        - application/json
      parameters:
        - name: email
          in: query
          description: email
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /v1/accounts/vinculation/cancel:
    get:
      tags:
        - account-controller
      summary: paypalVinculationCancel
      operationId: paypalVinculationCancelUsingGET
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /v1/tyc:
    get:
      tags:
        - tyc-controller
      summary: getLastTyc
      operationId: getLastTycUsingGET
      produces:
        - "*/*"
      parameters:
        - name: x-mine-user-id
          in: header
          description: x-mine-user-id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Tyc"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /v1/accounts/vinculation-setup:
    post:
      tags:
        - account-controller
      summary: afterVinculation
      operationId: afterVinculationUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: present
          in: query
          required: false
          type: boolean
        - in: body
          name: vinculationSetupDto
          description: vinculationSetupDto
          required: true
          schema:
            "$ref": "#/definitions/VinculationSetupDto"
        - name: x-mine-user-id
          in: header
          description: x-mine-user-id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  Account:
    type: object
    properties:
      access_token_v2:
        type: string
      activation_date:
        type: string
      bank_account_number:
        type: string
      client_id:
        type: integer
        format: int32
      code_verification:
        type: string
      desactivation_date:
        type: string
      email:
        type: string
      id:
        type: integer
        format: int32
      is_bank_account_active:
        type: boolean
      is_email_send:
        type: boolean
      login_date:
        type: string
      multicaja_bank_id:
        type: string
      operation_type:
        type: string
      origin_account_paypal:
        type: string
      origin_register_multicaja:
        type: string
      paypal_account_state:
        type: string
      paypal_account_status:
        type: string
      paypal_id:
        type: string
      paypal_type:
        type: string
      preapproval:
        type: string
      preapproval_date_end:
        type: string
      preapproval_date_start:
        type: string
      refresh_token_v2:
        type: string
      status_flow_register:
        type: integer
        format: int32
      type_document_sii_id:
        type: integer
        format: int32
      update_date:
        type: string
      user_bank_account_id:
        type: string
      user_bank_type_account_id:
        type: string
    title: Account
  Link:
    type: object
    properties:
      href:
        type: string
      templated:
        type: boolean
    title: Link
  Map«string,Link»:
    type: object
    title: Map«string,Link»
    additionalProperties:
      "$ref": "#/definitions/Link"
  ModelAndView:
    type: object
    properties:
      empty:
        type: boolean
      model:
        type: object
      modelMap:
        type: object
        additionalProperties:
          type: object
      reference:
        type: boolean
      status:
        type: string
        enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
      view:
        "$ref": "#/definitions/View"
      viewName:
        type: string
    title: ModelAndView
  Transaction:
    type: object
    properties:
      account_id:
        type: integer
        format: int64
      commission_multicaja:
        type: string
      commission_paypal:
        type: string
      create_date:
        type: string
        format: date-time
      dollar_amount:
        type: string
      dollar_amount_without_commission:
        type: string
      dollar_close:
        type: string
      dollar_id:
        type: integer
        format: int64
      dollar_multicaja_value:
        type: string
      dollar_value:
        type: string
      email_client:
        type: string
      email_send_date:
        type: string
        format: date-time
      id:
        type: integer
        format: int64
      if_send_email:
        type: integer
        format: int32
      liquidation_date:
        type: string
        format: date-time
      mc_code:
        type: integer
        format: int64
      operation_type:
        type: string
      pay_key:
        type: string
      paypal_request:
        type: string
      paypal_response:
        type: string
      paypal_tracking_id:
        type: string
      response:
        type: string
      response_date:
        type: string
        format: date-time
      return_amount:
        type: string
      status_response:
        type: string
      transaction_amount:
        type: string
      transaction_status_id:
        type: integer
        format: int32
      type_document_sii_id:
        type: integer
        format: int32
      update_date:
        type: string
        format: date-time
    title: Transaction
  Tyc:
    type: object
    properties:
      account_id:
        type: integer
        format: int64
      created_at:
        type: string
        format: date-time
      id:
        type: integer
        format: int64
      id_tenpo_paypal:
        type: integer
        format: int64
      paypal_status:
        type: boolean
      paypal_tyc_url:
        type: string
      tenpo_id:
        type: string
      type:
        type: string
      updated_at:
        type: string
        format: date-time
      version:
        type: integer
        format: int32
    title: Tyc
  View:
    type: object
    properties:
      contentType:
        type: string
    title: View
  VinculationSetupDto:
    type: object
    properties:
      account_id:
        type: integer
        format: int64
      email:
        type: string
      id_tenpo_paypal:
        type: integer
        format: int64
      token:
        type: string
    title: VinculationSetupDto