swagger: "2.0"
info:
  version: 1.0.0
  title: Paymentkyc API
host: 52.147.169.246:8080
basePath: /v1/payments-kyc
schemes:
  - http
paths:
  /recharge/category:
    get:
      produces:
        - application/json
      parameters:
        - name: access-token
          in: header
          required: true
          type: string
      responses:
        "200":
          description: 200 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "400":
          description: 400 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "401":
          description: 401 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "500":
          description: 500 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
  "/recharge/company/{companyId}":
    get:
      produces:
        - application/json
      parameters:
        - name: access-token
          in: header
          required: true
          type: string
        - name: companyId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: 200 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "400":
          description: 400 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "401":
          description: 401 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "500":
          description: 500 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
  /recharge/suggested:
    get:
      produces:
        - application/json
      parameters:
        - name: access-token
          in: header
          required: true
          type: string
      responses:
        "200":
          description: 200 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "400":
          description: 400 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "401":
          description: 401 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "500":
          description: 500 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
    post:
      produces:
        - application/json
      parameters:
        - name: access-token
          in: header
          required: true
          type: string
        - in: body
          name: RechargeSuggestedDto
          required: true
          schema:
            $ref: "#/definitions/RechargeSuggestedDto"
      responses:
        "200":
          description: 200 response
          schema:
            $ref: "#/definitions/PaymentOrder"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "201":
          description: 201 response
        "400":
          description: 400 response
        "401":
          description: 401 response
        "403":
          description: 403 response
        "404":
          description: 404 response
        "422":
          description: 422 response
          schema:
            $ref: "#/definitions/ResponseStatus"
  "/recharge/suggested/{suggestedId}":
    delete:
      produces:
        - application/json
      parameters:
        - name: suggestedId
          in: path
          required: true
          type: string
        - name: access-token
          in: header
          required: true
          type: string
      responses:
        "200":
          description: 200 response
          schema:
            $ref: "#/definitions/PaymentOrder"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "201":
          description: 201 response
        "400":
          description: 400 response
        "401":
          description: 401 response
        "403":
          description: 403 response
        "404":
          description: 404 response
        "422":
          description: 422 response
          schema:
            $ref: "#/definitions/ResponseStatus"
  "/recharge/{categoryId}/company":
    get:
      produces:
        - application/json
      parameters:
        - name: categoryId
          in: path
          required: true
          type: string
        - name: access-token
          in: header
          required: true
          type: string
      responses:
        "200":
          description: 200 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "400":
          description: 400 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "401":
          description: 401 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        "500":
          description: 500 response
          schema:
            $ref: "#/definitions/ResponseStatus"
          headers:
            X-Requested-With:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
definitions:
  ResponseStatus:
    type: object
    properties:
      code:
        type: string
        description: The HTTP code
      message:
        type: string
        description: A description message
  RechargeSuggestedDto:
    type: object
    properties:
      id:
        type: string
        format: uuid
      categoryId:
        type: string
        format: uuid
      companyId:
        type: string
        format: uuid
      companyCode:
        type: string
      paymentIdentifier:
        type: string
  PaymentOrder:
    type: object
    properties:
      accountId:
        type: string
        format: uuid
      amount:
        type: number
      currency:
        type: string
      description:
        type: string
      id:
        type: string
        format: uuid
      merchant:
        $ref: "#/definitions/Merchant"
      paymentCode:
        type: string
      processedDate:
        type: string
        format: date-time
      requestedDate:
        type: string
        format: date-time
      state:
        type: string
        enum:
          - PENDING
          - CANCELED
          - REQUESTED
          - CONFIRMED
      type:
        type: string
        enum:
          - IN
          - OUT
    title: PaymentOrder
  Merchant:
    type: object
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
    title: Merchant
