swagger: '2.0'
info:
  version: 1.0.0
  title: Api Documentation
host: 40.89.250.208:8080
basePath: /v1/payment-paypal
paths:
  /v1/accounts:
    get:
      summary: getRetiroAccountByClientId
      operationId: getRetiroAccountByClientIdUsingGET
      produces:
        - application/json
      parameters:
        - name: client_id
          in: query
          description: client_id
          required: true
          type: integer
          format: int64
        - name: operation_type
          in: query
          description: operation_type
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
