swagger: "2.0"
info:
  version: 1.0.0
  title: Payment-Online - Tenpo private API - Payment-Online
basePath: /v1/payment-online
schemes:
- http
paths:
  /cashout_online:
    post:
      tags:
      - payment-online
      summary: 'Permite realizar CashOut Online (TEF)'
      operationId: processCashOutDefered
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: header
          name: x-mine-user-id
          type: string
          required: true
        - in: body
          name: body
          schema:
            $ref: "#/definitions/CashOutDTO"
      responses:
        200:
          description: successful operation
          schema:
            items:
              $ref: "#/definitions/CashOutDTO"
  /utilities/bank:
    get:
      tags:
      - payment-online-utilities
      summary: 'Listado de bancos con sus codigos'
      operationId: listOfBank
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/BankDto"
  /utilities/account_type:
    get:
      tags:
      - payment-online-utilities
      summary: 'Listado tipos de cuenta'
      operationId: findAll
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/AccountTypeDto"
  /utilities/tenpo/bank_account/principal:
    get:
      tags:
      - payment-online-utilities
      summary: 'Obtiene la cuenta principal de tenpo'
      responses:
        200:
          description: successful operation
          schema:
            items:
              $ref: "#/definitions/TenpoBankAccountDto"
definitions:
  CashOutDTO:
    type: object
    properties:
      amount:
        description: Monto que se ha depositado
        $ref: '#/definitions/AmountDto'
      account_run:
        description: Rut del due침o de la cuenta
        type: string
      account_number:
        description: Numero de cuenta a donde va a transferir
        type: string
      account_type:
        type: string
        enum:
        - 'Cuenta corriente'
        - 'Cuenta vista'
        - 'Cuenta ahorro'
        - 'Cuenta rut'
      sbif_code:
        description: Identificador Sbif del banco
        type: integer 
      account_name:
        description: Nombre Due침o Cta
        type: string
      account_email:
        description: Email a quien informar cuando se complete transferencia
        type: string
  AmountDto:
    type: object
    properties:
      currency_code:
        type: string
        description: Codigo del tipo de moneda del dep칩sito
      value:
        type: number
        description: Monto del dep칩sito
    title: AmountDto
    description: Clase u objeto que representa el monto en el proceso de CashIn
 
  BankDto:
    type: object
    properties:
      id:
        type: string
        description: UUID Banco
      name:
        type: string
        description: Nombre Banco
      sbif_code:
        type: integer
        description: Codigo Sbif del Banco
  
  AccountTypeDto:
    type: object
    properties:
      id:
        type: string
        description: UUID Banco
      name:
        type: string
        description: Nombre Banco
  
  TenpoBankAccountDto:
    type: object
    properties:
      id:
        type: string
        description: UUID Banco
      name:
        type: string
        description: Nombre Cuenta
      bank_name:
        type: string
        description: Nombre Banco
      account_type:
        type: string
        description: Tipo de Cuenta
      account_number:
        type: string
        description: Numero de cuenta
      rut:
        type: string
        description: Rut
      email:
        type: string
        description: Correo electronico
      state:
        type: string
        description: Estado
