swagger: "2.0"
info:
  version: 1.0.0
  title: Transactions API
host: 40.70.202.107:8080
basePath: /v1/account-management
schemes:
  - http
paths:
  "/accounts/{userId}/on-site/generate-code":
    post:
      tags:
        - transaction-cash-in-api-controller
      summary: generate-code
      operationId: generateCodeUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: userId
          in: path
          description: userId
          required: true
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          schema:
            type: string
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
definitions: {}
