swagger: "2.0"
info:
  title: Utility Payments
  version: 1.0.0
host: tenpo.dev.multicajadigital.cloud
basePath: /v1/utility-payments
schemes:
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    in: header
    name: Authorization
paths:
  /welcome:
    post:
      responses:
        200:
          description: successful operation
  /categories:
    get:
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Category"
  /categories/{id}/utilities:
    get: 
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          minimum: 1
          description: The category ID
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Utility"
  /utilities/{id}/bills:
    post:
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          minimum: 1
          description: The utility ID
        - in: body
          name: body
          schema:
            $ref: "#/definitions/UtilityBillRequest"
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/UtilityBillResponse"
  /bills/{id}:
    get: 
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: string
          minimum: 1
          description: The bill ID
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/UtilityBillResponse"
  /transactions:
    post:
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/TransactionRequest"
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/TransactionResponse"
  # /transactions/{id}:
  #   get: 
  #     produces:
  #       - application/json
  #     parameters:
  #       - in: path
  #         name: id
  #         required: true
  #         type: string
  #         minimum: 1
  #         description: The transaction ID
  #     responses:
  #       200:
  #         description: successful operation
  #         schema:
  #           $ref: "#/definitions/TransactionResponse"
  /favorites:
    get:
      parameters:
        - in: header
          name: x-mine-user-id
          type: string
          required: true
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Favorite'
    post:
      parameters:
        - in: header
          name: x-mine-user-id
          type: string
          required: true
        - in: body
          name: body
          schema:
            $ref: "#/definitions/FavoriteRequest"
      responses:
        200:
          description: successful operation (already created)
          schema:
            $ref: '#/definitions/Favorite'
        201:
          description: successful operation
          schema:
            $ref: '#/definitions/Favorite'
  /favorites/{id}:
    delete:
      parameters: 
        - in: header
          name: x-mine-user-id
          type: string
          required: true
        - in: path
          name: id
          type: string
          required: true
          description: Id de la cuenta favorita
      responses:
        200:
          description: successful operation
        404:
          description: resource not found
        500:
          description: internal server error
  /options:
    get:
      responses:
        200:
          description: successful operation
        404:
          description: not found
    put:
      responses:
        200:
          description: successful operation
  /suggestions:
    get:
      responses:
        200:
          description: successful operation
  /home:
    get:
      responses:
        200:
          description: successful operation
definitions:
  Category:
    type: object
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: Agua
      utilities:
        type: integer
        example: 14
  Favorite:
    type: object
    properties:
      id:
        type: integer
        example: 1
      identifier:
        type: string
        example: 12345678
      utility:
        $ref: '#/definitions/Utility'
  FavoriteRequest:
    type: object
    properties:
      utility_id:
        type: integer
        example: 1
      identifier:
        type: string
        example: "123123"
  Utility:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      name:
        type: string
        example: Mundo Pacífico
      identifier:
        type: string
        example: "RUT, CON DIGITO VERIFICADOR"
  UtilityBillRequest:
    type: object
    properties:
      identifier:
        type: string
        example: 66823334
  UtilityBillResponse:
    type: object
    properties:
      id:
        type: string
        example: "fb7c3a5f-1db0-4ba0-ab72-a58db5f55f10"
      status:
        type: string
        example: WAITING
      utility:
        $ref: '#/definitions/Utility'
      identifier:
        type: string
        example: 66823334
      amount: 
        type: integer
        example: 5467
      due_date:
        type: string
        example: No disponible
      description:
        type: string
        example: Deuda Total
      created:
        type: string
        example: "2019-06-14T12:48:24.039-04:00"
  TransactionRequest:
    type: object
    properties:
      bills:
        type: array
        items:
          type: string
          example: "2019-06-14T12:48:24.039-04:00"
  TransactionResponse:
    type: object
    properties:
      id:
        type: string
        example: 51d95fc6-58e9-4bb0-a622-031cf08edc9c
      status:
        type: string
        example: WAITING
      order:
        type: string
        example: 120190424105826006
      user:
        type: string
        example: bdb7cd6d-dfca-4aee-82b0-4588e871ec79
      amount:
        type: integer
        example: 7639
      bills:
        type: array
        items:
          $ref: '#/definitions/UtilityBillResponse'
      created:
        type: string
        example: "2019-04-24T10:58:26.140605-04:00"
      updated:
        type: string
        example: "2019-04-24T10:58:26.140605-04:00"