stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

swagger-validation:
  stage: build
  image: swaggerapi/swagger-codegen-cli:2.4.5
  artifacts:
    paths:
      - bin/
  script:
    - generate -i /builds/krealomine/api/src/private/v1/accounts.yaml -l swagger -o /builds/krealomine/api/bin/private/v1/accounts

.config-deploy:
  stage: deploy
  image: mcr.microsoft.com/powershell:6.2.0-alpine-3.8
  script:
    - $ApiMgmtContext = New-AzApiManagementContext -ResourceGroupName $RG_NAME -ServiceName $SV_NAME

release-deploy:
  extends: .config-deploy
  only:
    - /^release.*$/
  environment:
    name: uat
  variables:
    RG_NAME: tenpo_uat
    SV_NAME: tenpo-uat-api-management