stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

swagger-validation:
  stage: build
  image: openjdk:8-jdk-alpine
  variables:
    CLI_VERSION: 2.4.5
  artifacts:
    paths:
      - bin/
  before_script:
    - wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/${CLI_VERSION}/swagger-codegen-cli-${CLI_VERSION}.jar -O /swagger-codegen-cli.jar
  script:
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/accounts.yaml -l swagger -o bin/private/v1/accounts
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/devices.yaml -l swagger -o bin/private/v1/devices
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/identityprovider.yaml -l swagger -o bin/private/v1/identityprovider
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/notifications.yaml -l swagger -o bin/private/v1/notifications
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/paymentkyc.yaml -l swagger -o bin/private/v1/paymentkyc
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/payments.yaml -l swagger -o bin/private/v1/payments
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/transactions.yaml -l swagger -o bin/private/v1/transactions
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/users.yaml -l swagger -o bin/private/v1/users
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/cards.yaml -l swagger -o bin/public/v1/cards
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/onboarding.yaml -l swagger -o bin/public/v1/onboarding
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/users.yaml -l swagger -o bin/public/v1/users

.config-deploy:
  stage: deploy
  image: mcr.microsoft.com/powershell:6.2.0-alpine-3.8
  script:
    - $ApiMgmtContext = New-AzApiManagementContext -ResourceGroupName $RG_NAME -ServiceName $SV_NAME

release-deploy:
  extends: .config-deploy
  only:
    - /^release.*$/
<<<<<<< HEAD
  environment:
    name: uat
  variables:
    RG_NAME: tenpo_uat
    SV_NAME: tenpo-uat-api-management
=======
  artifacts:
    paths:
      - bin/
  environment:
    name: uat
  variables:
    AZURE_TENANT_ID: $AZURE_TENANT_UAT_ID
    RESOURCE_GROUP_NAME: tenpo_uat
    SERVICE_NAME: tenpo-uat-api-management
>>>>>>> develop
