stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

swagger-validation:
  stage: build
  image: openjdk:8-jdk-alpine
  only:
    - master
    - develop
    - /^release.*$/
  variables:
    CLI_VERSION: 2.4.5
  artifacts:
    paths:
      - bin/
  before_script:
    - wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/${CLI_VERSION}/swagger-codegen-cli-${CLI_VERSION}.jar -O /swagger-codegen-cli.jar
  script:
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/accountsAndTransactions.yaml -l swagger -o bin/private/v1/accountsAndTransactions
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/devices.yaml -l swagger -o bin/private/v1/devices
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/identityprovider.yaml -l swagger -o bin/private/v1/identityprovider
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/notifications.yaml -l swagger -o bin/private/v1/notifications
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/paymentkyc.yaml -l swagger -o bin/private/v1/paymentkyc
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/payments.yaml -l swagger -o bin/private/v1/payments
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/users.yaml -l swagger -o bin/private/v1/users
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/cards.yaml -l swagger -o bin/private/v1/cards
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/appconfig.yaml -l swagger -o bin/public/v1/appconfig
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/onboarding.yaml -l swagger -o bin/public/v1/onboarding
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/users.yaml -l swagger -o bin/public/v1/users
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/launch.yaml -l swagger -o bin/public/v1/launch
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/payments.yaml -l swagger -o bin/public/v1/payments
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/validateUsers.yaml -l swagger -o bin/public/v1/validateUsers
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/utilityPayments.yaml -l swagger -o bin/private/v1/utilityPayments
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/payment-online.yaml -l swagger -o bin/private/v1/paymentOnline
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/prelaunch.yaml -l swagger -o bin/public/v1/prelaunch
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/users-eecc.yaml -l swagger -o bin/public/v1/users-eecc
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/payment-online.yaml -l swagger -o bin/public/v1/paymentOnline
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/transactionHistory.yaml -l swagger -o bin/private/v1/transactionsHistory
.config-deploy:
  stage: deploy
  image: jaxkodex/powershell-az
  script:
    - pwsh src/import.ps1

dev-deploy:
  extends: .config-deploy
  only:
    - develop
  artifacts:
    paths:
      - bin/
  environment:
    name: dev
  variables:
    RESOURCE_GROUP_NAME: tenpo_dev
    AZURE_TENANT_ID: $AZURE_TENANT_ID_DEV
    SERVICE_NAME: tenpo-dev-api-management
    AZURE_ACCOUNT_NAME: $AZURE_ACCOUNT_NAME_DEV
    AZURE_ACCOUNT_PASSWORD: $AZURE_ACCOUNT_PASSWORD_DEV
    USERS_IP: 40.70.68.63
    LAUNCH_IP: 104.208.140.16
    ACCOUNT_IP: 52.167.62.186
    IDENTITPROVIDER_IP: 40.123.26.42
    TRANSACTIONS_IP: 40.70.202.107
    NOTIFICATION_IP: 52.179.169.65
    PAYMENTS_IP: 52.179.131.53
    PAYMENTSKYC_IP: 52.147.169.246
    CARDS_IP: 40.79.18.220
    API_PREPAID: api.dev.multicajadigital.cloud
    API_UTILITY_PAYMENT: 104.209.159.135
    API_PAYMENTS_TOPUP: tenpo.dev.multicajadigital.cloud
    AUTH_URL: https://tenpodev2.b2clogin.com/
    USER_FLOW_NAME: B2C_1_ROPC_mobile
    CLIENT_ID: 5cba8f4d-b819-4903-a414-732dbd4b8378
    AZURE_TENANT_NAME: tenpodev2.onmicrosoft.com
    AZURE_B2C_TENANT_ID: cae09fee-473e-48e2-99dc-3b7bf4a97411
    USER_SUBSCRIPTION_KEY: 80450f7d0b6d481382113073f67822c3
    PAYMENT_SUBSCRIPTION_KEY: 80450f7d0b6d481382113073f67822c4
    TENPO_PRELAUNCH_API_IP: 172.11.0.134
    PAYMENT_ONLINE_SUBSCRIPTION_KEY: 3e132ca6ccbb4000d1ec2f5d362e6694
    TRANSACTION_HISTORY_IP: 52.225.220.194
uat-deploy:
  extends: .config-deploy
  only:
    - /^release.*$/
  artifacts:
    paths:
      - bin/
  environment:
    name: uat
  variables:
    RESOURCE_GROUP_NAME: tenpo_uat
    AZURE_TENANT_ID: $AZURE_TENANT_ID_DEV
    SERVICE_NAME: tenpo-uat-api-management
    AZURE_ACCOUNT_NAME: $AZURE_ACCOUNT_NAME_DEV
    AZURE_ACCOUNT_PASSWORD: $AZURE_ACCOUNT_PASSWORD_DEV
    USERS_IP: 172.11.0.135
    LAUNCH_IP: 0.0.0.0
    ACCOUNT_IP: 172.11.0.133
    IDENTITPROVIDER_IP: 172.11.0.136
    TRANSACTIONS_IP: 172.11.0.139
    NOTIFICATION_IP: 172.11.0.137
    PAYMENTS_IP: 172.11.0.138
    PAYMENTSKYC_IP: 0.0.0.0
    CARDS_IP: 172.11.0.140
    API_PREPAID: api.uat.multicajadigital.cloud
    #API_PREPAID: "20.50.1.4:31400"
    API_UTILITY_PAYMENT: 172.11.0.129
    API_PAYMENT_ONLINE: 172.11.0.145
    API_PAYMENTS_TOPUP: tenpo.uat.multicajadigital.cloud
    AUTH_URL: https://uattenpo2.b2clogin.com/
    USER_FLOW_NAME: B2C_1_ROPC_tenpo_uat
    CLIENT_ID: e9cfc90e-ee75-49a6-b765-4e74093b2878
    AZURE_TENANT_NAME: uattenpo2.onmicrosoft.com
    AZURE_B2C_TENANT_ID: c3fdc983-c30f-4c4e-b7e9-29502a5a7ee5
    USER_SUBSCRIPTION_KEY: 80450f7d0b6d481382113073f67822c5
    PAYMENT_SUBSCRIPTION_KEY: 80450f7d0b6d481382113073f67822c6
    TENPO_PRELAUNCH_API_IP: 172.11.0.155
    PAYMENT_ONLINE_SUBSCRIPTION_KEY: 429eb73edb580769df2a6f7686e9ee8d
    TRANSACTION_HISTORY_IP: 172.11.0.130
prod-deploy:
  extends: .config-deploy
  only:
    - master
  artifacts:
    paths:
      - bin/
  environment:
    name: prod
  variables:
    RESOURCE_GROUP_NAME: tenpo_prod_resource_group
    #RESOURCE_GROUP_NAME: tenpo_drp
    AZURE_TENANT_ID: $AZURE_TENANT_ID_PROD
    SERVICE_NAME: tenpo-prod-api-management
    #SERVICE_NAME: tenpo-drp-api-management
    AZURE_ACCOUNT_NAME: $AZURE_ACCOUNT_NAME_PROD
    AZURE_ACCOUNT_PASSWORD: $AZURE_ACCOUNT_PASSWORD_PROD
    USERS_IP: 172.11.0.36
    LAUNCH_IP: 0.0.0.0
    ACCOUNT_IP: 172.11.0.37
    IDENTITPROVIDER_IP: 172.11.0.38
    TRANSACTIONS_IP: 172.11.0.43
    NOTIFICATION_IP: 172.11.0.39
    PAYMENTS_IP: 172.11.0.42
    PAYMENTSKYC_IP: 0.0.0.0
    CARDS_IP: 172.11.0.40
    VERIFIER_IP: 172.11.0.106
    API_PAYMENT_ONLINE: 172.11.0.109
    API_PREPAID: "10.80.1.5:31400"
    API_UTILITY_PAYMENT: 172.11.0.144
    API_PAYMENTS_TOPUP: 172.11.0.151
    AUTH_URL: https://tenpoapp.b2clogin.com/
    USER_FLOW_NAME: B2C_1_ROPC_tenpo
    CLIENT_ID: 0b9c4aeb-9a1a-4ee4-a18e-94b01df49e5e
    AZURE_TENANT_NAME: tenpoapp.onmicrosoft.com
    AZURE_B2C_TENANT_ID: 30db1526-4fa2-4f4a-ae85-6d1e64e29171
    USER_SUBSCRIPTION_KEY: 80450f7d0b6d481382113073f67822c6
    PAYMENT_SUBSCRIPTION_KEY: 80450f7d0b6d481382113073f67822c7
    TENPO_PRELAUNCH_API_IP: 172.11.0.219
    PAYMENT_ONLINE_SUBSCRIPTION_KEY: a94e65d34ca8457c66900b7ea43d8ac8
    TRANSACTION_HISTORY_IP: 172.11.0.107