stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

swagger-validation:
  stage: build
  image: openjdk:8-jdk-alpine
  variables:
    CLI_VERSION: 2.4.5
  artifacts:
    paths:
      - bin/
  before_script:
    - wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/${CLI_VERSION}/swagger-codegen-cli-${CLI_VERSION}.jar -O /swagger-codegen-cli.jar
  script:
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/accountsAndTransactions.yaml -l swagger -o bin/private/v1/accountsAndTransactions
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/devices.yaml -l swagger -o bin/private/v1/devices
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/identityprovider.yaml -l swagger -o bin/private/v1/identityprovider
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/notifications.yaml -l swagger -o bin/private/v1/notifications
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/paymentkyc.yaml -l swagger -o bin/private/v1/paymentkyc
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/payments.yaml -l swagger -o bin/private/v1/payments
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/users.yaml -l swagger -o bin/private/v1/users
    - java -jar /swagger-codegen-cli.jar generate -i src/private/v1/cards.yaml -l swagger -o bin/private/v1/cards
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/appconfig.yaml -l swagger -o bin/public/v1/appconfig
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/onboarding.yaml -l swagger -o bin/public/v1/onboarding
    - java -jar /swagger-codegen-cli.jar generate -i src/public/v1/users.yaml -l swagger -o bin/public/v1/users

.config-deploy:
  stage: deploy
  image: jaxkodex/powershell-az
  script:
    - pwsh src/import.ps1

release-deploy:
  extends: .config-deploy
  only:
    - /^release.*$/
  artifacts:
    paths:
      - bin/
  environment:
    name: uat
  variables:
    RESOURCE_GROUP_NAME: tenpo_uat
    AZURE_TENANT_ID: $AZURE_TENANT_UAT_ID
    SERVICE_NAME: tenpo-uat-api-management
    AZURE_ACCOUNT_NAME: $AZURE_ACCOUNT_NAME
    AZURE_ACCOUNT_PASSWORD: $AZURE_ACCOUNT_PASSWORD
    USERS_IP: 172.11.0.129
    ACCOUNT_IP: 172.11.0.131
    IDENTITPROVIDER_IP: 172.11.0.133
    TRANSACTIONS_IP: 172.11.0.137
    NOTIFICATION_IP: 172.11.0.134
    PAYMENTS_IP: 172.11.0.130
    PAYMENTSKYC_IP: 0.0.0.0
    CARDS_IP: 172.11.0.132
    AUTH_URL: https://tenpodev2.b2clogin.com/
    USER_FLOW_NAME: B2C_1_ROPC_mobile
    CLIENT_ID: 5cba8f4d-b819-4903-a414-732dbd4b8378
    AZURE_TENANT_NAME: uattenpo2.onmicrosoft.com
    AZURE_B2C_TENANT_ID: cae09fee-473e-48e2-99dc-3b7bf4a97411
