swagger: '2.0'
info:
  version: 1.0.0
  title: Cards - Tenpo public API
host: 40.79.18.220:8080
basePath: /v1/cards-management
schemes:
  - http
paths:
  '/cards/{userId}':
    get:
      tags:
        - cards-controller
      summary: getCardsByUserId
      operationId: getCardsByUserIdUsingGET
      produces:
        - '*/*'
      parameters:
        - name: userId
          in: path
          description: userId
          required: true
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ObfuscatedCardsResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/cards/{userId}/details':
    get:
      tags:
        - cards-controller
      summary: getCardDetailByUserId
      operationId: getCardByUserIdUsingGET
      produces:
        - '*/*'
      parameters:
        - name: userId
          in: path
          description: userId
          required: true
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CardInfoResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  CardInfoResponse:
    type: object
    properties:
      expiration_date:
        type: integer
        format: int32
      id:
        type: string
      name_on_card:
        type: string
      pan:
        type: string
      security_code:
        type: integer
        format: int32
      status:
        type: string
      timestamps:
        $ref: '#/definitions/TimestampsExtDto'
    title: CardInfoResponse
  ObfuscatedCardsResponse:
    type: object
    properties:
      id:
        type: string
      name_on_card:
        type: string
      pan:
        type: string
      status:
        type: string
      timestamps:
        $ref: '#/definitions/TimestampsExtDto'
    title: ObfuscatedCardsResponse
  TimestampsExtDto:
    type: object
    properties:
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
    title: TimestampsExtDto