swagger: "2.0"
info:
  version: 1.0.0
  title: Login-ms - Tenpo public API
basePath: /v1/login-management
  - http
paths:
  /login:
     post:
      tags:
      - Login
      summary: 'Permite a un usaurio realizar log-in'
      operationId: login
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: Ocp-Apim-Subscription-Key
        description: Ocp-Apim-Subscription-Key
        required: true
        type: string
      - in: body
        name: LoginRequest
        description: Objeto para login
        required: true
        schema:
          $ref: '#/definitions/LoginRequest'
      responses:
        '201':
          description: Login Success
          schema:
            $ref: '#/definitions/LoginResonse'
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
        '404':
          description: Credenciales invalidas
        '422':
          description: Errores controlados
        '500':
          description: Ocurrió un error inesperado
definitions:
  LoginRequest:
    type: object
    properties:
      email:
        type: string
        description: Email Usuario login
      password:
        type: string
        description: Clabe usuario login
      app:
        type: string
        description: En que aplication te logueas.
        enum: [APP, WEBPAY] 
        
  LoginResonse:
    type: object
    properties:
      token_type:
        type: string
        description: Tipo de token
      access_token:
        type: string
        description: Token de Acceso