swagger: '2.0'
info:
  version: 1.0.0
  title: Onboarding - Tenpo public API - Onboarding
host: 40.70.68.63:8080
basePath: /v1/onboarding
schemes:
  - http
paths:
  '/users':
    post:
      tags:
        - mobile-on-boarding-controller
      summary: create
      operationId: createUsingPOST
      consumes:
        - application/json
      produces:
        - 'application/json'
      parameters:
        - in: body
          name: userInfoRequest
          description: userInfoRequest
          required: true
          schema:
            $ref: '#/definitions/UserInfoRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OnBoardingResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/users/{id}/address':
    patch:
      tags:
        - mobile-on-boarding-controller
      summary: updateAddress
      operationId: updateAddressUsingPATCH
      consumes:
        - application/json
      produces:
        - 'application/json'
      parameters:
        - in: body
          name: addressInfoRequest
          description: addressInfoRequest
          required: true
          schema:
            $ref: '#/definitions/AddressRequest'
        - name: id
          in: path
          description: id
          required: true
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OnBoardingResponse'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
  '/users/{id}/confirm-device':
    patch:
      tags:
        - mobile-on-boarding-controller
      summary: confirmPhone
      operationId: confirmPhoneUsingPATCH
      consumes:
        - application/json
      produces:
        - 'application/json'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
          format: uuid
        - in: body
          name: request
          description: request
          required: true
          schema:
            $ref: '#/definitions/ConfirmDeviceRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OnBoardingResponse'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
  '/users/{id}/password':
    post:
      tags:
        - mobile-on-boarding-controller
      summary: updatePassword
      operationId: updatePasswordUsingPOST
      consumes:
        - application/json
      produces:
        - 'application/json'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
          format: uuid
        - in: body
          name: passwordRequest
          description: passwordRequest
          required: true
          schema:
            $ref: '#/definitions/PasswordRequest'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/users/{id}/validate':
    patch:
      tags:
        - mobile-on-boarding-controller
      summary: updateIdentity
      operationId: updateIdentityUsingPATCH
      consumes:
        - application/json
      produces:
        - 'application/json'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
          format: uuid
        - in: body
          name: identityInfoRequest
          description: identityInfoRequest
          required: true
          schema:
            $ref: '#/definitions/IdentityInfoRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OnBoardingResponse'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
  '/users/{id}/validate-device':
    patch:
      tags:
        - mobile-on-boarding-controller
      summary: updatePhone
      operationId: updatePhoneUsingPATCH
      consumes:
        - application/json
      produces:
        - 'application/json'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
          format: uuid
        - in: body
          name: request
          description: request
          required: true
          schema:
            $ref: '#/definitions/ValidateDeviceRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OnBoardingResponse'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
  '/users/{id}/resend-verification-code':
    post:
      tags:
        - mobile-on-boarding-controller
      summary: resendVerificationCode
      operationId: resendVerificationCodeUsingPOST
      consumes:
        - application/json
      produces:
        - 'application/json'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
          format: uuid
        - in: body
          name: request
          description: request
          required: true
          schema:
            $ref: '#/definitions/UserPhoneRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OnBoardingResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/v1/onboarding/users/{id}/validate-email':
      post:
        tags:
          - mobile-on-boarding-controller
        summary: changeUserStatus
        operationId: changeUserStatusUsingPOST
        consumes:
          - application/json
        produces:
          - '*/*'
        parameters:
          - name: id
            in: path
            description: id
            required: true
            type: string
        responses:
          '200':
            description: OK
            schema:
              $ref: '#/definitions/UserDTO'
          '201':
            description: Created
          '401':
            description: Unauthorized
          '403':
            description: Forbidden
          '404':
            description: Not Found
        deprecated: false
definitions:
  ValidateDeviceRequest:
    type: object
    properties:
      phoneNumber:
        type: string
      userId:
        type: string
        format: uuid
    title: ValidateDeviceRequest
  AddressRequest:
    type: object
    properties:
      address:
        type: string
      regionCode:
        type: integer
        format: int32
    title: AddressRequest
  IdentityInfoRequest:
    type: object
    properties:
      documentNumber:
        type: string
      terms:
        type: boolean
      tributaryIdentifier:
        type: string
    title: IdentityInfoRequest
  UserEntity:
    type: object
    properties:
      address:
        type: string
      agreeTermsConditions:
        type: boolean
      countryCode:
        type: integer
        format: int32
      documentNumber:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
        format: uuid
      lastName:
        type: string
      level:
        type: string
        enum:
          - LEVEL_1
          - LEVEL_2
      nationality:
        type: string
      phone:
        type: string
      plan:
        type: string
        enum:
          - FREE
          - PREMIUM
      profession:
        type: string
      regionCode:
        type: integer
        format: int32
      state:
        type: string
        enum:
          - PENDING
          - VALIDATED
          - UNCONFIRMED
          - CONFIRMED
          - ACTIVE
          - BLOCKED
          - BLACKLIST
      tributaryIdentifier:
        type: string
      verificationCode:
        type: string
    title: UserEntity
  OnBoardingResponse:
    type: object
    properties:
      user:
        $ref: '#/definitions/UserEntity'
    title: OnBoardingResponse
  PasswordRequest:
    type: object
    properties:
      password:
        type: string
    title: PasswordRequest
  Region:
    type: object
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
    title: Region
  UserInfoRequest:
    type: object
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      nationality:
        type: string
      profession:
        type: string
    title: UserInfoRequest
  UserPhoneRequest:
    type: object
    properties:
      phoneNumber:
        type: string
    title: UserPhoneRequest
  ConfirmDeviceRequest:
    type: object
    properties:
      code:
        type: string
      userId:
        type: string
        format: uuid
    title: ConfirmDeviceRequest
