swagger: "2.0"
info:
  version: 1.0.0
  title: Payment - Tenpo public API - Payment
host: 52.179.131.53:8080
basePath: /v1/integration/payment/cl/on-site
schemes:
- http
paths:
  /cash-in:
    post:
      tags:
      - payment-on-site-controller
      summary: 'Permite realizar el cashIn físico, Este servicio sera llamado desde el POS'
      operationId: processCashInUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: validateCashInDto
        description: validateCashInDto
        required: true
        schema:
          $ref: '#/definitions/CashInDto'
      responses:
        '201':
          description: CashIn Procesado correctamente
          schema:
            $ref: '#/definitions/CashInResponseDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: El cliente no existe
        '422':
          description: El cliente no existe
        '500':
          description: Ocurrió un error inesperado
      deprecated: false
  /cash-in/reverse:
    post:
      tags:
      - payment-on-site-controller
      summary: Permite realizar la reversa de un CashIn físico realizado en las últimas 24 horas.Este servicio sera llamado desde el POS
      operationId: processCashInReverseUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: reverse
        description: reverse
        required: true
        schema:
          $ref: '#/definitions/ReverseDTO'
      responses:
        '201':
          description: CashIn correcto. Se iniciará el proceso de reversa.
        '202':
          description: '130001: CashIn no se recibió. Registrando reversa. 130003. Reversa ya fue recibida'
          schema:
            $ref: '#/definitions/ResponseEntity'
        '400':
          description: Error en parámetros enviados
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Cliente no existe o no  tiene prepago
        '410':
          description: Plazo para reversa expirado
        '422':
          description: Información de Reversa no concuerda
        '500':
          description: Error indeterminado
      deprecated: false
  /cash-out:
    post:
      tags:
      - payment-on-site-controller
      summary: 'Permite realizar el cashOut físico, Este servicio sera llamado desde el POS'
      operationId: processCashOutUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: validateCashInDto
        description: validateCashInDto
        required: true
        schema:
          $ref: '#/definitions/CashOutDto'
      responses:
        '201':
          description: CashOut Procesado correctamente
          schema:
            $ref: '#/definitions/CashInResponseDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: El recurso que trataste de alcanzar no fue encontrado
        '500':
          description: Ocurrió un error inesperado
      deprecated: false
  /cash-out/reverse:
    post:
      tags:
      - payment-on-site-controller
      summary: Permite realizar la reversa de un CashOut físico realizado en las últimas 24 horas.Este servicio sera llamado desde el POS
      operationId: processCashOutReverseUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: reverse
        description: reverse
        required: true
        schema:
          $ref: '#/definitions/ReverseDTO'
      responses:
        '201':
          description: CashOut correcto. Se iniciará proceso de reversa.
        '202':
          description: '130001: CashOut no se recibió. Registrando reversa.130003. Reversa ya fue recibida'
          schema:
            $ref: '#/definitions/ResponseEntity'
        '400':
          description: Error en parámetros enviados
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Cliente no existe o no  tiene prepago
        '410':
          description: Plazo para reversa expirado
        '422':
          description: Información de Reversa no concuerda
        '500':
          description: Error indeterminado
      deprecated: false
definitions:
  ReverseDTO:
    type: object
    properties:
      amount:
        description: Monto que se ha depositado
        $ref: '#/definitions/AmountDto'
      merchant_category:
        type: string
        description: Categoria del comercio donde se realizó el depósito
      merchant_code:
        type: string
        description: Codigo del comercio donde se realizó el depósito
      merchant_name:
        type: string
        description: Nombre del comercio donde se realizó el depósito
      rut:
        type: string
        description: Rut del usuario TENPO
      transaction_id:
        type: string
        description: Id de la transación generado desde el POS
    title: ReverseDTO
    description: Objeto que identifica una transaccion a reversar
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
        enum:
        - '100'
        - '101'
        - '102'
        - '103'
        - '200'
        - '201'
        - '202'
        - '203'
        - '204'
        - '205'
        - '206'
        - '207'
        - '208'
        - '226'
        - '300'
        - '301'
        - '302'
        - '303'
        - '304'
        - '305'
        - '307'
        - '308'
        - '400'
        - '401'
        - '402'
        - '403'
        - '404'
        - '405'
        - '406'
        - '407'
        - '408'
        - '409'
        - '410'
        - '411'
        - '412'
        - '413'
        - '414'
        - '415'
        - '416'
        - '417'
        - '418'
        - '419'
        - '420'
        - '421'
        - '422'
        - '423'
        - '424'
        - '426'
        - '428'
        - '429'
        - '431'
        - '451'
        - '500'
        - '501'
        - '502'
        - '503'
        - '504'
        - '505'
        - '506'
        - '507'
        - '508'
        - '509'
        - '510'
        - '511'
      statusCodeValue:
        type: integer
        format: int32
    title: ResponseEntity
  CashInDto:
    type: object
    properties:
      agencyCode:
        type: string
        description: Codigo de la agencia donde se realiza el depósito
      amount:
        description: Monto del depósito
        $ref: '#/definitions/AmountDto'
      dynamic_token:
        type: string
        description: Token dinamico generado desde el app tenpo
      merchant_category:
        type: string
        description: Categoria del comercio donde se realiza el depósito
      merchant_code:
        type: string
        description: Codigo del comercio donde se realiza el depósito
      merchant_name:
        type: string
        description: Nombre del comercio donde se realiza el depósito
      rut:
        type: string
        description: Rut del usuario tenpo
      transaction_id:
        type: string
        description: Id de la transación generado desde el POS
    title: CashInDto
  CashOutDto:
    type: object
    properties:
      agencyCode:
        type: string
        description: Codigo de la agencia donde se realiza el retiro
      amount:
        description: Monto del depósito
        $ref: '#/definitions/AmountDto'
      dynamic_token:
        type: string
        description: Token dinamico generado desde el app tenpo
      merchant_category:
        type: string
        description: Categoria del comercio donde se realiza el retiro
      merchant_code:
        type: string
        description: Codigo del comercio donde se realiza el retiro
      merchant_name:
        type: string
        description: Nombre del comercio donde se realiza el retiro
      rut:
        type: string
        description: Rut del usuario tenpo
      transaction_id:
        type: string
        description: Id de la transación generado desde el POS
    title: CashInDto
    description: 'Clase u objeto que representa los datos que son enviados desde el POS, para realizar un CashIn'
  CashInResponseDto:
    type: object
    properties:
      amount:
        description: Monto que se ha depositado
        $ref: '#/definitions/AmountExternalDto'
      id:
        type: string
        description: Id de la operación
      mcVoucherDataDto:
        type: array
        description: Voucher de la transación
        items:
          $ref: '#/definitions/PaymentConfigDto'
      timestampsDto:
        description: timestampsDto
        $ref: '#/definitions/PaymentConfigDto'
      transactionId:
        type: string
        description: Id de la transación
    title: CashInResponseDto
    description: Clase u objeto que representa la respuesta del procesador para un CashIn
  PhysicalPointDto:
    type: object
    properties:
      points:
        type: array
        items:
          $ref: "#/definitions/PointDto"
    title: PhysicalPointDto
  PointDto:
    type: object
    properties:
      address:
        type: string
      commerce:
        type: string
      latitude:
        type: number
        format: float
      longitude:
        type: number
        format: float
    title: PointDto
  PaymentConfigDto:
    type: object
    properties:
      createdAt:
        type: string
        format: date-time
        description: Id de usuario
      updatedAt:
        type: string
        format: date-time
        description: Id de usuario
    title: PaymentConfigDto
    description: Clase u objeto que representa una configuración de pago
  AmountExternalDto:
    type: object
    properties:
      currencyCode:
        type: integer
        format: int32
      value:
        type: number
    title: AmountExternalDto
  AmountDto:
    type: object
    properties:
      currency_code:
        type: string
        description: Codigo del tipo de moneda del depósito
      value:
        type: number
        description: Monto del depósito
    title: AmountDto
    description: Clase u objeto que representa el monto en el proceso de CashIn
