swagger: '2.0'
info:
  version: 1.0.0
  title: UsersExternal - Tenpo public API - UsersExternal
host: 40.70.68.63:8080
basePath: /v1/webhook-user-management/
schemes:
  - http
paths:
  '/users/{userId}/identity-validation':
    post:
      tags:
      - upgrade-user-controller
      summary: validateIdentity
      operationId: validateIdentityUsingPOST
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - in: body
        name: identityValidationDto
        description: identityValidationDto
        required: true
        schema:
          $ref: '#/definitions/IdentityValidationDto'
      - name: userId
        in: path
        description: userId
        required: true
        type: string
        format: uuid
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  IdentityValidationDto:
    type: object
    properties:
      gesintel_approved:
        type: string
      picture_validate:
        type: string
      retry_allowed:
        type: string
      retry_number:
        type: integer
        format: int32
      rut_validate:
        type: string
      ticket_id:
        type: string
    title: IdentityValidationDto
